main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('about/', views.about, name='about-name'),
    path('uslugi/', views.uslugi, name='uslugi'),
    path('prices/', views.prices, name='prices'),
    path('enter_post/', views.text_enter, name='text_enter'),
    path('update_post/<int:id>/<str:title_name>/', views.prices_enter, name='prices_enter'),
    path('enter/', views.prices_enter, name='prices_enter'),
    path('list/', views.all_text, name='all_text'),
    path('text_edit/<str:title>/<int:id>/', views.text_edit, name="text_edit"),
   # path("prices/<int:id>/edit/", views.category_edit, name="category_edit"),
    path("prices/<int:id>/delete/", views.category_delete, name="category_delete"),
    path("prices/<int:id>/<str:name>/edit/", views.product_edit, name="product_edit"),
    path("prices/<int:id>/<str:name>/delete/", views.product_delete, name="product_delete"),
    path('', views.index, name='index'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mamontov/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as authViews
from users import views as vs

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('main.urls')), 
    path('logout/', vs.logoutPage, name="logout"),
    path('login/', vs.loginPage, name ='login'),
    path('users/', include('users.urls')),

]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
	
    path('users/registration/', views.register, name='registration'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
                                                                 name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_sent.html"), 
                                                                 name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_form.html"), 
                                                                                name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_done.html"), 
                                                                                  name="password_reset_complete"),]

users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from PIL import Image
from django.conf import settings

User = get_user_model()

class ManagerUser(models.Model):
    manager = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name=models.CharField(max_length=200, null=True)
    date = models.DateTimeField(default=timezone.now)
    profile_pic=models.ImageField(default='default.png',
                                  null=True, blank=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    customer=models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='customer')
    username=models.CharField(max_length=191, null=True, blank=True)
    first_name=models.CharField(max_length=200, null=True, blank=True)
    last_name=models.CharField(max_length=200, null=True, blank=True)
    address=models.CharField(max_length=200, null=True, blank=True)
    phone=models.CharField(max_length=200, null=True)
    email=models.EmailField(max_length=200, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)
    img=models.ImageField(default='default.png', upload_to='media/user_image')

    def __str__(self):
        return self.customer.username
    
    def save(self, *args, **kwargs):
        super(Customer, self).save(*args, **kwargs)
        image = Image.open(self.img.path)
        if image.height > 360 or image.width > 240:
            resize = (360, 240)
            image.thumbnail(resize)
            image.save(self.img.path)

            

users/forms.py
from django import forms
from django.contrib.auth.forms import User
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone
from .models import *
from django.contrib.auth import get_user_model
from django.forms import ModelForm
User = get_user_model()


class ProfileForm(UserCreationForm):
    username=forms.CharField(max_length=191,
                         label='Логин')

    first_name=forms.CharField(max_length=200, 
                               label='Имя', 
                               required=False, 
                               widget=forms.TextInput({ "placeholder": "Иван" }))

    last_name=forms.CharField(max_length=200,
                                label='Фамилия',
                                required=False,
                                widget=forms.TextInput({ "placeholder": "Иванов" }))

    email=forms.EmailField(required=True,
                           max_length=200,
                           label='Email',
                           widget=forms.TextInput({ "placeholder": "ivan@mail.ru" }))

    class Meta:
        model = User
        fields = ('username', 'first_name','last_name', 'email', 'password1', 'password2')



class ProfileFullForm(ModelForm):

    username=forms.CharField(max_length=50,
                             label='Логин')

    first_name=forms.CharField(max_length=200, 
                               label='Имя', 
                               required=False, 
                               widget=forms.TextInput({ "placeholder": "Иван" }))

    last_name=forms.CharField(max_length=200,
                                label='Фамилия',
                                required=False,
                                widget=forms.TextInput({ "placeholder": "Иванов" }))

                                
    address=forms.CharField(max_length=200,
                            label='Адрес',
                            required=False, 
                            widget=forms.Textarea({ "placeholder": "г. Краснознаменск, ул. Победы, дом 6, корп. 5, 1 подъезд, 9 эт., кв.32", 'rows':6,
                                                    'cols':30,
                                                    'style':'resize:none;'}))

    phone=forms.CharField(max_length=200,
                          label='Номер телефона',
                          widget=forms.TextInput({ "placeholder": "+79851234567" }))

    email=forms.EmailField(required=True,
                           max_length=200,
                           label='Email',
                           widget=forms.TextInput({ "placeholder": "ivan@mail.ru" }))
    img=forms.ImageField(required=True,
                           max_length=200,
                           label='Фото',
                           widget=forms.FileInput)                       
    class Meta:
        model = Customer
        fields = ('username', 'first_name','last_name', 'email', 'address', 'phone', 'img')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
from .models import *
from django.contrib.auth.models import User, Group
from .decorators import unauthenticated_user, allowed_users, admin_only

@unauthenticated_user
def register (request):
    form = ProfileForm()
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            customer=form.save()
            customer.user=request.user
            group = Group.objects.get(name='customers')
            customer.groups.add(group)
            customer.save()
            messages.success(request, f"Создан аккаунт пользователя {request.user.username}")
            return redirect('main:index')    
    context = {'form':form, 'title':'Регистрация нового пользователя'}
    return render(request, 'users/registration.html', context)




@unauthenticated_user
def loginPage(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password =request.POST.get('password')

		user = authenticate(request, username=username, password=password)

		if user is not None:
			login(request, user)
			return redirect('index')
		else:
			messages.info(request, 'Логин или пароль неправильные')

	context = {}
	return render(request, 'users/login.html', context)



def logoutPage(request):
	logout(request)
	return redirect('/')

users/templates/users/exit.html
{% extends 'blog/main.html'%}

{% block main_section%}
    <div class="form-section">
            <h2>Вы успешно вышли из аккаунта!</h2>
      <a href="{% url 'user'%}">Войти в личный кабинет</a>
    </div>   
{%endblock%}




{%block aside_new%}

<img src="https://i.ibb.co/hL54dRs/story-wu.jpg"width="100%" height="100%">
    <p><strong>Узнай о том как эти ребята начинали свой путь.</strong></p>
    <a href="/history" target="_blank">
        <button type="button" class="btn btn-dark">Узнать больше</button>
    </a>


{%endblock aside_new%}

users/templates/users/full_registration.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}


<div class="row inline-block-row">
{% block content%}
                
            <div class="col-12 col-md-6 col-sm-5 col-lg-3">
                <div class="card text-center text-black mb-3" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                    -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                    -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                    border-radius: 5px;" id='total-orders'>
                        <hr>
                        <h3 style="text-align: center">Моя страница</h3>
                        <hr>
                        <img class="rounded" src="{{request.user.customer.img.url}}" >
                        <h2 style="text-align: center">{{request.user.customer.name}}</h2>
                        <a class="btn btn-warning" href="{% url 'epix:index' %}"> &#8592; Назад </a>
                    </div>

            
                    <div class="card text-center text-black mb-3" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                    -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                    -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                    border-radius: 5px;" id='total-orders'>
                            <form method="POST" enctype="multipart/form-data">
                                <h2>НАСТРОЙКА СТРАНИЦЫ</h2>
                                {% csrf_token %}
                                {{ update_user|crispy}}
                                {{img_profile}}
                                <button type="submit" class="btn-dark">Подтвердить</button>
                            </form>
                    </div>   
            </div>

                <div class="col-9 col-md-9 col-sm-9 col-lg-9 ">
                    <div class="card text-center text-black mb-3" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                        border-radius: 5px;font-size:19px; text-overflow: ellipsis; white-space: nowrap;overflow: hidden;" id='total-orders'>
                    {% include "users/orders_table.html" %} 
                    </div>  
                </div>  


    </div>
{%endblock%}

</div>

users/templates/users/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Логин..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Пароль..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'users:registration' %}" class="ml-2">Sign Up</a>
					</div>
					<div class="mt-4">
						<div class="d-flex justify-content-center links">
							Забыли пароль? <a href="{% url 'users:reset_password' %}" class="ml-2">Восстановить</a>
						</div>
				
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

users/templates/users/orders_table.html
    <table class='table table-striped w-auto'>
        <thead>
        <tr class="table-info">
            <th>Имя: </th>
            <th>Фамилия: </th>
            <th>Почта: </th>
            <th>Адрес: </th> 
            <th>Индекс: </th>
            <th>Город: </th>
            <th>Дата заказа: </th>
            <th>Дата обновления: </th>
            <th>Оплачен: </th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for ord in orders%}
        <tr>
            <td>{{ord.first_name}}</td>
            <td>{{ord.last_name}}</td>
            <td>{{ord.email}}</td>
            <td>{{ord.address}}</td>
            <td>{{ord.postal_code}}</td>
            <td>{{ord.city}}</td>
            <td>{{ord.created}}</td>
            <td>{{ord.updated}}</td>
            <td>{{ord.paid}}</td>                    
            <td><a href="">Обновить</a></td>
            <td><a href="">Удалить</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

users/templates/users/password_reset.html
  
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">
	
</form>

users/templates/users/password_reset_done.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="/">Log in</a>

users/templates/users/password_reset_form.html
<h3>Enter new password</h3>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Update Password">
	
</form>

users/templates/users/password_reset_sent.html
<h3>Password reset sent</h3>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

users/templates/users/profile.html
{% extends 'blog/main.html'%}
{% block main_section%}

    <div class="form-section">
            <h2>Кабинет пользователя </h2>
    <div class="media text-muted pt-3">

      <img class="mr-2 rounded" style = " width: 64px; height: 64px;" src="{{ user.profile.img.url}}" >
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">@{{user.username}}</strong>
        <b>Email:</b> {{ user.email}}
      </p>
    </div>        
    <h3 class="mt-4">Изменить данные </h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_user.as_p }}
        {{ img_profile.as_p }}
        <button type="submit" class="btn-dark">Обновить</button>
    </form>

    </div>

{%endblock%}




{%block aside_new%}

<img src="https://i.ibb.co/hL54dRs/story-wu.jpg"width="100%" height="100%">
    <p><strong>Узнай о том как эти ребята начинали свой путь.</strong></p>
    <a href="/history" target="_blank">
        <button type="button" class="btn btn-dark">Узнать больше</button>
    </a>


{%endblock aside_new%}

users/templates/users/registration.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}
{% block title %} Последние обновления {% endblock %}

{% block content%}
    <div class="container" style="font-family: 'Gill Sans'; font-size: 20px;">
    <div class="form-section card mb-5" style="background-color: #32B2CD;">
        <div class='offset-3 col-9 col-sm-6 card mb-5 mt-3'>
        <form method="POST">
            <h2>Регистрация на сайте</h2>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="card center-block">
            <button type="submit" class="btn-dark center-block" >Зарегистрироваться</button></div>
        </form>
        <hr>
        <div class="card center-block text-center mb-3"> Уже зарегистрированы?<a href="{% url 'login'%}">Войти в личный кабинет</a></div>
        </div>
    </div>
</div>
{%endblock content%}



{%block aside_new%}

<img src="https://sun9-41.userapi.com/c856024/v856024070/48d7d/BYpnDxzoiXY.jpg"width="30%" height="30%">
    <p><strong>Узнай о том как эти ребята начинали свой путь.</strong></p>
    <a href="/history" target="_blank">
        <button type="button" class="btn btn-dark">Узнать больше</button>
    </a>


{%endblock aside_new%}

users/templates/users/sign_up.html
{% extends 'blog/main.html'%}
{% block main_section%}

    <div class="form-section">
        <form method="POST">
            <h2>Регистрация на сайте</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-dark">Зарегистрироваться</button>
        </form>
        <hr>
        Уже зарегистрированы? <a href="sign_up">Войти в личный кабинет</a>
    </div>

{%endblock%}




{%block aside_new%}

<img src="https://i.ibb.co/hL54dRs/story-wu.jpg"width="100%" height="100%">
    <p><strong>Узнай о том как эти ребята начинали свой путь.</strong></p>
    <a href="/history" target="_blank">
        <button type="button" class="btn btn-dark">Узнать</button>
    </a>


{%endblock aside_new%}

users/templates/users/user.html
{% extends 'index.html'%}
{% block content%}

    <div class="form-section">
        <form method="POST">
            <h2>Авторизация на сайте</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-dark">Войти</button>
            <button type="submit" class="btn-red">Восстановить пароль</button>
        </form>
        <hr>
        Нет аккаунта? <a href="">Создать пользователя</a> 
    </div>

{%endblock%}




{%block aside_new%}

<img src="https://i.ibb.co/hL54dRs/story-wu.jpg"width="100%" height="100%">
    <p><strong>Узнай о том как эти ребята начинали свой путь.</strong></p>
    <a href="/history" target="_blank">
        <button type="button" class="btn btn-dark">Узнать</button>
    </a>


{%endblock aside_new%}